[m5]
   path = /home/utylee
   #path = /home/utylee/temp
   browseable = yes
   read only = no
   writable = yes
   guest ok = yes
   create mask = 0777
   directory mask = 0777

[4002]
   path = /home/utylee/media/4002
   browseable = yes
   read only = no
   writable = yes
   guest ok = yes
   create mask = 0777
   directory mask = 0777

[3002]
   path = /home/utylee/media/3002
   browseable = yes
   read only = no
   writable = yes
   guest ok = yes
   create mask = 0777
   directory mask = 0777

[4001]
   path = /home/utylee/media/4001
   browseable = yes
   read only = no
   writable = yes
   guest ok = yes
   create mask = 0777

[8001]
   path = /home/utylee/media/8001
   browseable = yes
   read only = no
   writable = yes
   guest ok = yes
   create mask = 0777
   directory mask = 0777
   directory mask = 0777
