[global]
    # 심볼릭 링크를 따라가도록 허용
    follow symlinks = yes
    
    # 공유 디렉토리 외부에 있는 링크도 허용 (가장 중요한 옵션)
    wide links = yes
    
    # wide links를 사용하기 위해 보안 옵션 해제 (필수)
    unix extensions = no


[m5]
   path = /home/utylee
   #path = /home/utylee/temp
   browseable = yes
   read only = no
   writable = yes
   guest ok = yes
   create mask = 0777
   directory mask = 0777

[4002]
   path = /home/utylee/media/4002
   browseable = yes
   read only = no
   writable = yes
   guest ok = yes
   create mask = 0777
   directory mask = 0777

[3002]
   path = /home/utylee/media/3002
   browseable = yes
   read only = no
   writable = yes
   guest ok = yes
   create mask = 0777
   directory mask = 0777

[4001]
   path = /home/utylee/media/4001
   browseable = yes
   read only = no
   writable = yes
   guest ok = yes
   create mask = 0777

[8001]
   path = /home/utylee/media/8001
   browseable = yes
   read only = no
   writable = yes
   guest ok = yes
   create mask = 0777
   directory mask = 0777
   directory mask = 0777
